# Usa una base image con Python
FROM python:3.10-slim

# Imposta la working directory all'interno del container
WORKDIR /app

# Copia il file requirements.txt per installare le dipendenze
COPY requirements.txt .

# Installa le dipendenze da requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia i file Python necessari nel container
COPY data_collector.py .
COPY circuit_breaker.py .

# Imposta il comando di esecuzione del DataCollector
CMD ["python", "data_collector.py"]
