apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s  # Intervallo di raccolta predefinito (30 secondi)
      evaluation_interval: 30s  # Intervallo di valutazione predefinito (30 secondi)
      external_labels:
        monitor: 'DSBD'

    scrape_configs:
      # Job per raccogliere le metriche da Prometheus stesso
      - job_name: 'prometheus'
        scrape_interval: 25s  # Intervallo di raccolta specifico per Prometheus
        static_configs:
          - targets:
              - localhost:9090  # Indirizzo del server Prometheus

      # Job per raccogliere le metriche dal server gRPC
      - job_name: 'server_grpc_exporter'  # Nome del job per l'exporter gRPC
        scrape_interval: 30s  # Intervallo di raccolta per il server gRPC
        static_configs:
          - targets:
              - 'servergrpc:8000'  # Aggiungi il target del server gRPC sulla porta 8000

      # Job per raccogliere le metriche dal data collector
      - job_name: 'data_collector_exporter'  # Nome del job per il data collector
        scrape_interval: 30s  # Intervallo di raccolta per il data collector
        static_configs:
          - targets:
              - 'datacollector:8002'  # Aggiungi il target del data collector sulla porta 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.46.0
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus  # Qui viene montato il file di configurazione
        - name: prometheus-data
          mountPath: /prometheus  # Per i dati di Prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config  # ConfigMap che contiene il file prometheus.yml
      - name: prometheus-data
        emptyDir: {}  # Puoi usare un PV se desideri persistenza dei dati

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090  # Porta esposta tramite NodePort
