# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Servizio per la gestione degli utenti
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/sistema_finanza.UserService/RegisterUser',
                request_serializer=service__pb2.UserRequest.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/sistema_finanza.UserService/UpdateUser',
                request_serializer=service__pb2.UserRequest.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/sistema_finanza.UserService/DeleteUser',
                request_serializer=service__pb2.UserRequest.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Servizio per la gestione degli utenti
    """

    def RegisterUser(self, request, context):
        """Registrazione utente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Aggiornamento utente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Eliminazione utente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=service__pb2.UserRequest.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=service__pb2.UserRequest.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=service__pb2.UserRequest.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sistema_finanza.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sistema_finanza.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Servizio per la gestione degli utenti
    """

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_finanza.UserService/RegisterUser',
            service__pb2.UserRequest.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_finanza.UserService/UpdateUser',
            service__pb2.UserRequest.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_finanza.UserService/DeleteUser',
            service__pb2.UserRequest.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StockServiceStub(object):
    """Servizio per la gestione dei valori azionari
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestStockValue = channel.unary_unary(
                '/sistema_finanza.StockService/GetLatestStockValue',
                request_serializer=service__pb2.StockRequest.SerializeToString,
                response_deserializer=service__pb2.StockResponse.FromString,
                _registered_method=True)
        self.GetAverageStockValue = channel.unary_unary(
                '/sistema_finanza.StockService/GetAverageStockValue',
                request_serializer=service__pb2.StockAverageRequest.SerializeToString,
                response_deserializer=service__pb2.StockAverageResponse.FromString,
                _registered_method=True)


class StockServiceServicer(object):
    """Servizio per la gestione dei valori azionari
    """

    def GetLatestStockValue(self, request, context):
        """Ultimo valore azionario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAverageStockValue(self, request, context):
        """Media dei valori azionari
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestStockValue,
                    request_deserializer=service__pb2.StockRequest.FromString,
                    response_serializer=service__pb2.StockResponse.SerializeToString,
            ),
            'GetAverageStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAverageStockValue,
                    request_deserializer=service__pb2.StockAverageRequest.FromString,
                    response_serializer=service__pb2.StockAverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sistema_finanza.StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sistema_finanza.StockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Servizio per la gestione dei valori azionari
    """

    @staticmethod
    def GetLatestStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_finanza.StockService/GetLatestStockValue',
            service__pb2.StockRequest.SerializeToString,
            service__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAverageStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_finanza.StockService/GetAverageStockValue',
            service__pb2.StockAverageRequest.SerializeToString,
            service__pb2.StockAverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
